### PR TITLE
fix markdown and broken docs link

### PR DESCRIPTION
**Pull request by alucic**
- [x] fix markdown link to zend-expressive repo
- [x] fix broken link to template docs

### CODE REVIEW

**Comment by geerteltink** [comment]
The correct location for the template docs would be: https://zendframework.github.io/zend-expressive/features/template/intro/

**Comment by alucic** [comment]
@xtreamwayz updated

**Comment by localheinz** [comment]
@weierophinney 

Any chance to take a look?

**Comment by weierophinney** [comment]
Thanks, @alucic

**Pull request merged**
